In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Import library yang dibutuhkan untuk melakukan preprocessing dataset

  1. Numpy merupakan library python yang digunakan untuk melakukan operasi numerik pada data, yang menyediakan berbagai fungsi matematika dan statistika yang dapat digunakan untuk mengolah data numerik dan komputasi matriks
  2. Pandas merupakan library python yang untuk mengolah dan menganalisis data, pandas menyediakan struktut data seperti Series dan DataFrame yang sangat berguna untuk mengelola data tabular , serta menyediakan berbagai fungsi untuk memanipulasi, membersihkan dan mengabungkan data.
  3. Matplotlib adalah library python yang diunakan untuk membuat visualisasi grafik dari data seperti chart, line chart, scatter plot etc.


In [ ]:

dataset = pd.read_csv('data/preprocessing.csv')
dataset.describe


melakukan import dataset ke dalam variable dataset dengan pandas

In [19]:
attribute_x = dataset.iloc[:, :-1].values
class_y = dataset.iloc[:, -1].values

print(attribute_x)
print(class_y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Memisahkan antara atribute dan class, dimana iloc merupakan library pandas yang digunakan untuk memisahkan column dari dataset

1. Memasukan attribute di column 1-3 kedalam variable attribute_x
2. Memasukan attribute di column 4 kedalam variable class_y

In [30]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(attribute_x[:, 1:])
attribute_x[:, 1:] = imputer.transform(attribute_x[:, 1:])


Mengubah nilai Nan menjadi nilai rata-rata menggunakan function SimpleImputer dari library sklearn.impute



In [31]:
print(attribute_x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
attribute_x = np.array(ct.fit_transform(attribute_x))


In [32]:
print(attribute_x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Mengubah nominal(field country) kedalam berntuk matriks di encoding kedalam bentuk matriks mengguakan function ColumnTransformer dan
OneHotEncoder untuk mengubah column contry kedalam bentuk matriks



In [33]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
class_y = label_encoder.fit_transform(class_y)

In [34]:
print(class_y)

[0 1 0 0 1 1 0 1 0 1]


Mengubah label(class) YES/NO kedalam bentuk numberik 
YES = 1
NO = 0
menggunakan LabelEncoder dari sklearn.preprocessing(khusus untuk label)

In [35]:
from sklearn.model_selection import train_test_split

attribute_x_train, attribute_x_test, class_y_train, class_y_test = train_test_split(attribute_x, class_y, test_size=0.2, random_state=1)


In [36]:
print(attribute_x_test)
print(attribute_x_train)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [37]:
print(class_y_test)
print(class_y_train)

[0 1]
[0 1 0 0 1 1 0 1]


Membagi dataset menjadi data training dan data testing baik untuk attribute_x maupun class_y menggunakan funtion train_test_split dari sklearn.model_selection
1. test_size = 0.2 maksudnya data test 20% data training 80%

In [38]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
attribute_x_train[:, 3:] = sc.fit_transform(attribute_x_train[:, 3:])
attribute_x_test[:, 3:] = sc.fit_transform(attribute_x_test[:, 3:])


In [41]:
print(attribute_x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [40]:
print(attribute_x_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]


Kendala : Skala umur dan salary terlalu besar maka
dalam komputasi harus di scale ke range yang lebih kecil kita scale di attribute_x_train dan attribute_x_train karena rangenya terlalu besar misal 20 dengan 40 ubah menjadi lebih dekat

In [42]:
print(attribute_x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [43]:
print(attribute_x_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]


In [44]:
print(class_y_train)

[0 1 0 0 1 1 0 1]


In [45]:
print(class_y_test)

[0 1]
